site_name:        ControlSystems.jl
repo_url:         https://github.com/JuliaControl/ControlSystems.jl
site_description: A control systems design toolbox for Julia.
site_author:      JuliaControl

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code

docs_dir: 'build'

pages:
  - Home: 'index.md'
  - Examples:
    - Design: 'examples/example.md'
  - Guide:
    - Introduction: 'man/introduction.md'
    - 'Creating Transfer Functions': 'man/creatingtfs.md'
  - Functions:
    - Constructors: 'lib/constructors.md'
    - Analysis: 'lib/analysis.md'
    - Synthesis: 'lib/synthesis.md'
    - 'Time and Frequency response': 'lib/timefreqresponse.md'
    - Plotting: 'lib/plotting.md'
